<a href="https://colab.research.google.com/github/RapaDewan/Machine-Learning/blob/main/Python/pyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
print('Rapa')

Rapa


In [51]:
7+7

14

In [52]:
2*3

6

In [53]:
10* 'rapa'

'raparaparaparaparaparaparaparaparaparapa'

In [54]:
type ('rapa')

str

In [55]:
type ('False')

str

In [56]:
#syntax
#var_names=values

b=100

type (b)

int

In [57]:
b=100
type (b)

int

In [58]:
a=5
b=2

print (a+b)
print (a-b)
print (a*3)
print (b*1.8)

7
3
15
3.6


In [59]:
first_name= "Rapa"
last_name= "Dewan"

print ("My first name is {} and my last name is {}." .format(first_name, last_name))

My first name is Rapa and my last name is Dewan.


In [60]:
first_name= "Rapa"
last_name= "Dewan"

print ("My first name is {first} and my last name is {last}." .format(last=last_name, first=first_name))

My first name is Rapa and my last name is Dewan.


In [61]:
len ('rapa dewan')

10

In [62]:
type ([1,2,3,4])

list

In [63]:
my_word= 'Rapa dewan'
my_word.istitle()

False

In [64]:
my_word= "Rapa"
my_word.startswith('R')


True

In [65]:
True and True

True

In [66]:
True or False

True

In [67]:
True and False

False

In [68]:
example= "Mash123"
my_exp= "rapa dewan"
example.isalnum() and my_exp.isalpha() #prblem

False

In [69]:
list_exp= []
type (list_exp)

list

In [70]:
lst=list()
lst= ["rapa",1,2,3]
type (lst)
len(lst)
lst.append("dewan")
print (lst)
lst[0]

['rapa', 1, 2, 3, 'dewan']


'rapa'

In [71]:
lst[:]

['rapa', 1, 2, 3, 'dewan']

In [72]:
lst[1:]

[1, 2, 3, 'dewan']

In [73]:
lst [1:4]

[1, 2, 3]

In [74]:
lst.append (['rapuu', 'mash'])
print (lst)

['rapa', 1, 2, 3, 'dewan', ['rapuu', 'mash']]


In [75]:
lst.insert (2,'raziv')
print (lst) //duibar kore ashe kno?

Object `kno` not found.


In [76]:
lst1=list()
lst1=[1,2,3,4]
type(lst1)

list

In [77]:
lst1.extend([5,6,7])
print (lst1) # DUIBAR KENO ASHE?

[1, 2, 3, 4, 5, 6, 7]


In [78]:
sum(lst1)

28

In [79]:
lst1.pop(5)

6

In [80]:
lst1.count(7)

1

In [81]:
lst1.count(5)

1

In [82]:
lst1.index(1,0,3) #0-3 er part bujhinai

0

In [83]:
min(lst1)

1

In [84]:
max(lst1)

7

In [85]:
2*lst1 #ulta palta sb

[1, 2, 3, 4, 5, 7, 1, 2, 3, 4, 5, 7]

In [86]:
set_var= set()
print(set_var)
type (set_var)
print (type(set_var))

set()
<class 'set'>


In [87]:
set_var={1,2,3,4,3}
set_var

{1, 2, 3, 4}

In [88]:
set_var1=set()
set_var1={'rapa','mash', 'aman', 'rapa'}
set_var1 #serially ashlo na kno??

{'aman', 'mash', 'rapa'}

In [89]:
dict()
type (dict())

dict

In [90]:
my_dict={'sec1':'mma','sec2':'mma1','sec3':'mma2'}
my_dict['sec2']

'mma1'

In [91]:
for x in my_dict:
  print (x)

sec1
sec2
sec3


In [92]:
for x in my_dict.values():
  print (x)

mma
mma1
mma2


In [93]:
for x in my_dict.items():
  print (x)

('sec1', 'mma')
('sec2', 'mma1')
('sec3', 'mma2')


In [94]:
my_dict['sec4']='mma3'
my_dict

{'sec1': 'mma', 'sec2': 'mma1', 'sec3': 'mma2', 'sec4': 'mma3'}

In [95]:
my_dict['sec1']='mma1'


In [96]:
#my_dict['mma1']

In [97]:
my_dict1={'sec1':'rapa', 'sec2':'mash', 'sec1':'aman'}
my_dict1['sec1']

'aman'

In [98]:
car1_mod={'Audi':1980}
car2_mod={'benz':1920}
car3_mod={'mars':1975}
car_type={'car1':car1_mod, 'car2':car2_mod, 'car3':car3_mod}
print (car_type)

{'car1': {'Audi': 1980}, 'car2': {'benz': 1920}, 'car3': {'mars': 1975}}


In [99]:
print (car_type['car1'])

{'Audi': 1980}


In [100]:
print (car_type['car1']['Audi'])

1980


In [101]:
my_tupl=('abc','def','ghi')
my_tupl,type(my_tupl),my_tupl[0]

(('abc', 'def', 'ghi'), tuple, 'abc')

In [103]:
#my_tupl[0]=('efg')

In [104]:
my_tupl=('efg','ijk','ijk')
my_tupl

('efg', 'ijk', 'ijk')

In [105]:
my_tupl.index('efg')

0

In [106]:
my_tupl.count('ijk')


2

##Video=>7##

In [107]:
import numpy as np

In [108]:
 my_lst=[1,2,3,4,5]
 arr=np.array(my_lst)
 type (arr)

numpy.ndarray

In [109]:
arr

array([1, 2, 3, 4, 5])

In [110]:
arr[3]

4

In [111]:
arr.shape

(5,)

In [112]:
my_lst1=[1,2,3,4,5]
my_lst2=[5,6,7,8,9]
my_lst3=[4,5,2,3,7]
arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 5, 2, 3, 7]])

In [113]:
arr.shape

(3, 5)

In [114]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 4, 5],
       [2, 3, 7]])

In [115]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
arr[5]

6

In [117]:
my_lst1=[1,2,3,4,5]
my_lst2=[5,6,7,8,9]
my_lst3=[4,5,2,3,7]
arr2=np.array([my_lst1,my_lst2,my_lst3])
arr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 5, 2, 3, 7]])

In [119]:
arr2[:,:]

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 5, 2, 3, 7]])

In [121]:
arr2[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [123]:
arr2[1:4,3:5]

array([[8, 9],
       [3, 7]])

In [124]:
arr2[1:,3:]

array([[8, 9],
       [3, 7]])

In [127]:
arr2=np.arrange(0,10,step=2)
arr2 #bujhinai eta

AttributeError: module 'numpy' has no attribute 'arrange'

In [129]:
arr2[3:]=65
arr2

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 5, 2, 3, 7]])

In [130]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
arr[3:]=65
arr

array([ 1,  2,  3, 65, 65, 65, 65, 65])

In [134]:
  arr4=arr
  arr4

array([ 1,  2,  3, 65, 65, 65, 65, 65])

In [135]:
arr4[3:]=500

In [136]:
arr4

array([  1,   2,   3, 500, 500, 500, 500, 500])

In [137]:
arr #replaced as arr4

array([  1,   2,   3, 500, 500, 500, 500, 500])

In [143]:
arr4=arr.copy()
arr4[3:]=1000
arr4,arr


(array([   1,    2,    3, 1000, 1000, 1000, 1000, 1000]),
 array([  1,   2,   3, 500, 500, 500, 500, 500]))

In [149]:
val=2
arr[arr<500]

array([1, 2, 3])

In [145]:
  arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000])

In [146]:
 arr/2

array([  0.5,   1. ,   1.5, 250. , 250. , 250. , 250. , 250. ])

In [151]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [153]:
np.ones((4,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [157]:
np.random.rand(4,4)

array([[0.98353434, 0.31982614, 0.4758445 , 0.06967227],
       [0.91159599, 0.76573615, 0.60660891, 0.62829595],
       [0.50750466, 0.06365741, 0.68956953, 0.96832752],
       [0.04345716, 0.78853998, 0.54272999, 0.34467629]])

In [158]:
import seaborn as sns
import pandas as pd

In [162]:
 np.random.randint(0,100,9).reshape(3,3)

array([[74, 37, 45],
       [ 5, 73, 75],
       [21,  5, 78]])

In [165]:
np.random.random_sample(1,5) #problem

TypeError: random_sample() takes at most 1 positional argument (2 given)