<a href="https://colab.research.google.com/github/RapaDewan/Machine-Learning/blob/main/Python/pyBasic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print('Rapa')

Rapa


In [ ]:
7+7

14

In [ ]:
2*3

6

In [ ]:
10* 'rapa'

'raparaparaparaparaparaparaparaparaparapa'

In [ ]:
type ('rapa')

str

In [ ]:
type ('False')

str

In [ ]:
#syntax
#var_names=values

b=100

type (b)

int

In [ ]:
b=100
type (b)

int

In [ ]:
a=5
b=2

print (a+b)
print (a-b)
print (a*3)
print (b*1.8)

7
3
15
3.6


In [ ]:
first_name= "Rapa"
last_name= "Dewan"

print ("My first name is {} and my last name is {}." .format(first_name, last_name))

My first name is Rapa and my last name is Dewan.


In [ ]:
first_name= "Rapa"
last_name= "Dewan"

print ("My first name is {first} and my last name is {last}." .format(last=last_name, first=first_name))

My first name is Rapa and my last name is Dewan.


In [ ]:
len ('rapa dewan')

10

In [ ]:
type ([1,2,3,4])

list

In [ ]:
my_word= 'Rapa dewan'
my_word.istitle()

False

In [ ]:
my_word= "Rapa"
my_word.startswith('R')


False

In [ ]:
True and True

True

In [ ]:
True or False

True

In [ ]:
True and False

False

In [ ]:
example= "Mash123"
my_exp= "rapa dewan"
example.isalnum() and my_exp.isalpha() #prblem

False

In [ ]:
list_exp= []
type (list_exp)

list

In [ ]:
lst=list()
lst= ["rapa",1,2,3]
type (lst)
len(lst)
lst.append("dewan")
print (lst)
lst[0]

['rapa', 1, 2, 3, 'dewan']


'rapa'

In [ ]:
lst[:]

['rapa', 1, 2, 3, 'dewan']

In [ ]:
lst[1:]

[1, 2, 3, 'dewan']

In [ ]:
lst [1:4]

[1, 2, 3]

In [ ]:
lst.append (['rapuu', 'mash'])
print (lst)

['rapa', 1, 2, 3, 'dewan', 'rapu, mash', 'rapu, mash', 'rapu, mash', ['rapuu', 'mash']]


In [ ]:
lst.insert (2,'raziv')
print (lst) //duibar kore ashe kno?

[511, 511, 'raziv', 'raziv', 'rapa', 1, 2, 3, 'dewan', 'rapu, mash', 'rapu, mash', 'rapu, mash', ['rapuu', 'mash']]


In [ ]:
lst1=list()
lst1=[1,2,3,4]
type(lst1)

list

In [ ]:
lst1.extend([5,6,7])
print (lst1) # DUIBAR KENO ASHE?

[1, 2, 3, 4, 5, 6, 7, 5, 6, 7]


In [ ]:
sum(lst1)

46

In [ ]:
lst1.pop(5)

6

In [ ]:
lst1.count(7)

1

In [ ]:
lst1.count(5)

2

In [ ]:
lst1.index(1,0,3) #0-3 er part bujhinai

0

In [ ]:
min(lst1)

1

In [ ]:
max(lst1)

7

In [ ]:
2*lst1 #ulta palta sb

[1, 2, 3, 4, 5, 7, 5, 6, 1, 2, 3, 4, 5, 7, 5, 6]

In [ ]:
set_var= set()
print(set_var)
type (set_var)
print (type(set_var))

set()
<class 'set'>


In [ ]:
set_var={1,2,3,4,3}
set_var

{1, 2, 3, 4}

In [ ]:
set_var1=set()
set_var1={'rapa','mash', 'aman', 'rapa'}
set_var1 #serially ashlo na kno??

{'aman', 'mash', 'rapa'}

In [2]:
dict()
type (dict())

dict

In [3]:
my_dict={'sec1':'mma','sec2':'mma1','sec3':'mma2'}
my_dict['sec2']

'mma1'

In [4]:
for x in my_dict:
  print (x)

sec1
sec2
sec3


In [7]:
for x in my_dict.values():
  print (x)

mma
mma1
mma2


In [8]:
for x in my_dict.items():
  print (x)

('sec1', 'mma')
('sec2', 'mma1')
('sec3', 'mma2')


In [9]:
my_dict['sec4']='mma3'
my_dict

{'sec1': 'mma', 'sec2': 'mma1', 'sec3': 'mma2', 'sec4': 'mma3'}

In [13]:
my_dict['sec1']='mma1'


NameError: name 'sec1' is not defined

In [11]:
my_dict['mma1']

KeyError: 'mma1'

In [15]:
my_dict1={'sec1':'rapa', 'sec2':'mash', 'sec1':'aman'}
my_dict1[sec1]

NameError: name 'sec1' is not defined

In [19]:
car1_mod={'Audi':1980}
car2_mod={'benz':1920}
car3_mod={'mars':1975}
car_type={'car1':car1_mod, 'car2':car2_mod, 'car3':car3_mod}
print (car_type)

{'car1': {'Audi': 1980}, 'car2': {'benz': 1920}, 'car3': {'mars': 1975}}


In [21]:
print (car_type['car1'])

{'Audi': 1980}


In [22]:
print (car_type['car1']['Audi'])

1980


In [27]:
my_tupl=('abc','def','ghi')
my_tupl,type(my_tupl),my_tupl[0]

(('abc', 'def', 'ghi'), tuple, 'abc')

In [28]:
my_tupl[0]=('efg')

TypeError: 'tuple' object does not support item assignment

In [35]:
my_tupl=('efg','ijk','ijk')
my_tupl

('efg', 'ijk', 'ijk')

In [32]:
my_tupl.index('efg')

0

In [36]:
my_tupl.count('ijk')


2

##Video=>7##

In [1]:
import numpy as np

In [2]:
 my_lst=[1,2,3,4,5]
 arr=np.array(my_lst)
 type (arr)

numpy.ndarray

In [3]:
arr

array([1, 2, 3, 4, 5])

In [10]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [4]:
arr.shape

(5,)

In [6]:
my_lst1=[1,2,3,4,5]
my_lst2=[5,6,7,8,9]
my_lst3=[4,5,2,3,7]
arr=np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [4, 5, 2, 3, 7]])

In [7]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 4, 5],
       [2, 3, 7]])

In [14]:
arr=np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
arr[5]

6